baseURL = 'https://andyphua114.github.io/'
languageCode = 'en-us'
title = 'Hello'
theme = 'hugo-theme-mini'

paginate = 5

googleAnalytics = "G-8WWJE6P22E"

# Site parameters
[params] 
# Site Author
author = 'Andy Phua'
# Author biography
bio = 'AI Engineer'
# Site Description, used in HTML meat
description = 'My Blog'
enableGoogleAnalytics = true

[markup.goldmark.renderer]
unsafe= true