baseURL = 'https://andyphua114.github.io/'
languageCode = 'en-us'
title = 'Hello'
theme = 'hugo-theme-mini'

paginate = 5

# Site parameters
[params] 
# Site Author
author = 'Andy Phua'
# Author biography
bio = 'Senior Data Analyst | Aspiring Data Scientist'
# Site Description, used in HTML meat
description = 'My Blog'